export const bathroom= [
    {
        id: "jsah38283uJCAB_jfi3",
        name: "ELEMENT S OGLEDALOM",
        price: 1999,
        description: "75x70x20 cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PI35B9brSjoDPkxIl0p-DN6g/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    },
    {
        id: "kjdsaoHDS893-JFFHkc2",
        name: "ELEMENT S OGLEDALOM hrast",
        price: 1099,
        description: "90x89x23 cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PIAxSjfw1OHAPQ9NN6jbUKFg/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    },
    {
        id: "JFB8474-qhuau",
        name: "ORMAR BOČNI ZA KUPAONICU",
        price: 799,
        description: "40x85x32 cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PIs6Gz-mabyk2foy1YBT8fEA/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    },
    {
        id: "9uv9qj-498qzvHVH",
        name: "OGLEDALO KUPAONSKO ",
        price: 1799,
        description: "90x70x3 cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PIjLqcqzhz9OeCU1-UR_XAGA/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    },
    {
        id: "JNAKVN90R4-vkbqij",
        name: "ELEMENT ISPOD UMIVAONIKA",
        price: 2499,
        description: "115x60x42  cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PI1msDSU2vxFmomgCklmyL2g/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    },
    {
        id: "ks.,mvk.rqofi9rfj",
        name: "VISOKI ELEMENT bijela",
        price: 1099,
        description: "65x195x33 cm",
        img: "https://media.xxxlutz.com/i/xxxlutz/PI09ly-ezhfjXA0wYQA0Z5JA/?fmt=auto&w=768&h=0&upscale=false",
        category: "bathroom",
    }
];